INFO = {
    'first_name': 'John',
    'last_name': 'Doe',
    'full_name': 'John Doe',
    'email': 'fake@fakerson.com',
    'phone': '555-555-5555',
    'current_company': 'Hydra',
    'resume': 'fake_resume.pdf',
    'linkedin': 'https://www.linkedin.com/',
    'website': 'google.com',
    'github': 'https://github.com',
    'twitter': 'www.twitter.com',
    'location': 'Los Angeles, California, United States',
    'grad_month': '12',
    'grad_year': '2008',
    'university': 'Hogwarts'}